[[redirects]]
from="/*"
to="/index.html"
status=200

[[headers]]
  for = "/*.glb"
    [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/*.gltf"
    [headers.values]
    Content-Type = "model/gltf+json"
